M48
; DRILL file KiCad 10.0.1 date 2026-08-02T15:45:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-02T15:45:45+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X9.03Y5.62
X9.03Y5.62
X13.94Y5.65
X16.23Y5.4
X20.99Y5.52
T2
X7.5Y7.4
X12.5Y7.4
X17.5Y7.4
X22.5Y7.4
M30
